add handlers
ca11ado/lapopo pull request #6
Opened 2020-11-23 07:51 UTC by IgorGram

2020-11-23 17:23 UTC, ca11ado requested changes

2020-11-23 17:23 UTC, ca11ado commented on .gitignore
> +server/http.http
А это кто такой?

2020-11-23 17:23 UTC, ca11ado commented on server/middleware/index.js
> +  app.keys = ['keys', 'keykeys'];
А это что?

2020-11-23 17:23 UTC, ca11ado commented on server/controllers/users.js
> +  ctx.session.pokers = pokers;
Что за `pokers`? При регистрации нам нужно только имя указать

2020-11-23 17:23 UTC, ca11ado commented on server/controllers/users.js
> +  ctx.session.name = name;
Нужна проверка на то, что такое имя ещё не было использовано

2020-11-23 17:24 UTC, IgorGram commented on .gitignore
> +server/http.http
это я локально тестирую ручки, мой файлик с запросами

2020-11-23 17:27 UTC, IgorGram commented on server/middleware/index.js
> +  app.keys = ['keys', 'keykeys'];
это ключи для шифрования, если чесно я не до конца понял тему шифрования кук в этих пакетах. Потом можно с шифрованием отдельно поработать

2020-11-23 17:27 UTC, IgorGram commented on server/controllers/users.js
> +  ctx.session.pokers = pokers;
у тебя в ручке нашел, или я не туда записал.....

2020-11-23 21:11 UTC, ca11ado commented on server/middleware/index.js
> +  app.keys = ['keys', 'keykeys'];
Тебе тут нужна какая-то уникальная строка. Видимо, это так называемая "соль", которая добавляется при шифровании, чтобы добавить уникальности шифрованию.
Вообще сейчас достаточно одной строчки, потому что несколько строчек сделано для ротации этих ключей.
Плюс, ты не можешь хранить эту строчку в публичном репозитории гитхаба, так как вся её секретность таким образом нивелируется)))

2020-11-23 21:18 UTC, ca11ado commented on server/controllers/users.js
> +  ctx.session.pokers = pokers;
Не, если ты у меня и увидел, то это какая-то моя ошибка, потому что нам в эту ручку нужно только имя пользователя класть

2020-11-23 21:20 UTC, ca11ado commented on server/controllers/users.js
> +  ctx.session.name = name;
Да, и нужна валидация имени, чтобы туда не могли всякую херню засунуть.
Что-нибудь вроде:
* больше двух и меньше 15 символов
* только буквы кириллицы и латиницы + пробел, всё остальное запрещаем

2020-12-06 07:20 UTC, ca11ado requested changes

2020-12-06 07:20 UTC, ca11ado commented on .env
> +SECRET_KEY="anton"
Удалить .env файл
Положить ключ в .env.local

2020-12-06 07:20 UTC, ca11ado commented on package.json
> +    "redis": "^3.0.2",
Delete

2020-12-06 07:20 UTC, ca11ado commented on package.json
> +    "koa-session": "^6.1.0",
Delete

2020-12-06 13:52 UTC, ca11ado approved these changes

2020-12-06 13:53 UTC, merged